export default {
  phoneNumber: 'Phone Number',
  emailAddress: 'Email Address',
  firstName: 'First Name',
  lastName: 'Last Name',
  companyName: 'Company Name',
  state: 'State',
  country: 'Country',
  fleet: 'Fleet#',
  advancedCustomerSearchButton: 'Advanced Customer Search',
  searchCustomer: 'Search by Customer',
  createNewCustomer: 'Create a New Customer',
  errorName: 'First and Last name are required to search',
  errorEmail: 'Email address is missing @ character or .com',
  errorPhoneNumber: 'Phone Number is invalid',
  phoneNumberLength: 10,
  textMaxLength: 50,
  scanVin: 'Scan VIN',
  scanQR: 'Scan QR',
  errorVin: 'Vin is missing characters.',
  searchByVin: 'Search by VIN',
  licensePlateNo: 'License Plate Number',
  searchByLicensePlateNo: 'Search by License Plate',
  noCustomerFoundError: 'No Customer Record found - try a different search',
  vin: 'VIN',
  vinScanResult: 'VIN Scan Result:',
  vehicleInformation: 'VEHICLE INFORMATION',
  scanError: 'We couldn’t find a match',
  tryAgainVin: 'Try again with a VIN that is clearly visible',
  scanAgain: 'Scan Again',
  typeVinManually: 'Type VIN Manually',
  reScan: 'RESCAN',
  scan: 'SCAN',
  done: 'DONE',
  yesClearSearch: 'Yes, Clear my Search',
  noReturnToSearch: 'No, Return to Search',
  selectVTV: 'Select a VTV',
  vinNoStatic: 'WBAVB12040KU95257',
  scanVinInfo1: '2015 FORD',
  scanVinInfo2: 'F-150 XLT EXTENDED CAB 4WD',
};
